version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/strings.db:/app/strings.db
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend/
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
